CREATE DATABASE IF NOT EXISTS `apprenant_db`;
CREATE DATABASE IF NOT EXISTS `brief_db`;
CREATE DATABASE IF NOT EXISTS `formateur_db`;
CREATE DATABASE IF NOT EXISTS `rendu_db`;
CREATE DATABASE IF NOT EXISTS `validation_db`;
